= 文档说明

== 项目环境

* SpringBoot 2.7.5
* JDK 11
* Gradle 7.6.1
* H2 数据库进行测试


== 目录结构说明

* http: 存放 http 接口请求文件
* sharding-hibernate：基于 Hibernate 实现分表操作（未完成）
* sharding-jpa：扩展 Spring Data Repository。自定义 JpaRepositoryFactoryBean 实现（未完成）
* sharding-shardingsphere：使用 ShardingSphere 完成（完成）
* sharding-demo：测试工程

== 系统说明

系统主要包含两个表 person,person_province。 person 表不需要分库分表，person_province 表需要根据 person 表中的 province 字段进行分表。

== 端点

[source,httprequest]
----

### 查询
GET http://localhost:8080/person/1

### 新增
POST http://localhost:8080/person
Content-Type: application/json

{
  "id": 6,
  "name": "jcohy06",
  "age": 30,
  "province": "陕西"
}

### 更新
POST http://localhost:8080/person
Content-Type: application/json

{
  "id": 6,
  "name": "jcohy06",
  "age": 33,
  "province": "杭州"
}

### 删除
DELETE http://localhost:8080/person/1

### 根据省份查询
GET http://localhost:8080/person/province/杭州
----

== 测试

在 sharding-demo 模块，启动 DemoApplication，系统在启动时会自动创建表和数据。

[source,java]
----
@Bean
CommandLineRunner commandLineRunner() {

    // 构造数据
    return args -> {
        personRepository.saveAll(List.of(
                new Person(1, "jcohy01", 21, "陕西"),
                new Person(2, "jcohy02", 22, "四川"),
                new Person(3, "jcohy03", 23, "湖南"),
                new Person(4, "jcohy04", 24, "上海"),
                new Person(5, "jcohy05", 25, "北京"),
                new Person(6, "jcohy06", 26, "安徽"),
                new Person(7, "jcohy07", 25, "陕西"),
                new Person(8, "jcohy08", 25, "四川"),
                new Person(9, "jcohy09", 25, "陕西"),
                new Person(10, "jcohy10", 25, "湖南")
        ));

        personProvinceRepository.saveAll(List.of(
                new PersonProvince(1,1,"陕西","陕西急诊记录","备注"),
                new PersonProvince(2,2,"四川","四川急诊记录","备注"),
                new PersonProvince(3,3,"湖南","湖南急诊记录","备注"),
                new PersonProvince(4,4,"上海","上海急诊记录","备注"),
                new PersonProvince(5,5,"北京","北京急诊记录","备注"),
                new PersonProvince(6,6,"安徽","安徽急诊记录","备注"),
                new PersonProvince(7,7,"陕西","安徽急诊记录","备注"),
                new PersonProvince(8,8,"四川","安徽急诊记录","备注"),
                new PersonProvince(9,9,"陕西","安徽急诊记录","备注"),
                new PersonProvince(10,10,"湖南","安徽急诊记录","备注")
        ));
    };
}
----


登录 h2 控制台。http://localhost:8080/h2-console/ ，账号密码都是：sa。我们可以看到，

* PERSON 表：10 条记录。
* PERSON_PROVINCE_1 表： 0 条记录
* PERSON_PROVINCE_2 表： 1 条记录，包含上海。
* PERSON_PROVINCE_3 表： 1 条记录，包含安徽。
* PERSON_PROVINCE_4 表： 2 条记录，包含湖南。
* PERSON_PROVINCE_5 表： 5 条记录，包含陕西，四川
* PERSON_PROVINCE_6 表： 1 条记录，包含北京

从上面可以看出，已经实现了分库分表，即同一省份的记录肯定在同一张表中。这里 PERSON_PROVINCE_5 表中包含了两个省份，时因为我们使用 哈希取余 算法。
不同省份有可能会在一张表中，但一个省份只能在一张表中。

另外，我们可以调用提供的增删改查接口来测试。

