= 文档说明

== 项目环境

* SpringBoot 2.7.5
* JDK 11
* Gradle 7.6.1
* H2 数据库进行测试

== 目录结构说明

* commons: 通用类库
* http: 存放 http 接口请求文件
* sharding-hibernate：基于 Hibernate 实现分表操作（未完成，新增和插入已完成）
* sharding-jpa：扩展 Spring Data Repository。自定义 JpaRepositoryFactoryBean 实现（未完成）
* sharding-shardingsphere：使用 ShardingSphere 完成（完成）
* sharding-demo：测试工程

== 系统说明

系统主要包含两个表 person,person_province。 person 表不需要分库分表，person_province 表需要根据 person 表中的 province 字段进行分表。

=== sharding-hibernate

此模块使用基于注解的方式实现。使用 `@Sharding` 和 `@ShardingField`  注解来标记需要进行分表的操作

* @Sharding：需要进行分表的实体
* @ShardingField：分表的字段，目前仅支持单字段。

=== sharding-jpa

=== sharding-shardingsphere

此模块使用配置文件的方式实现。以下是一个简单的配置示例：

[source,yaml]
----
include::sharding-demo/src/main/resources/application.yaml[]
----

[NOTE]
====
所有实现目前仅支持单数据源
====

== HTTP 端点

[source,httprequest]
----
include::http/http.http[]
----

== 测试

打开 sharding-demo 模块的下的 build.gradle 文件。导入您需要测试的模块，如下：

[source,groovy]
----
dependencies {
	implementation(project(":sharding-shardingsphere"))
}
----

在 sharding-demo 模块，启动 DemoApplication，系统在启动时会自动创建表和数据。

[source,java,indent=0]
----
include::sharding-demo/src/main/java/com/demo/DemoApplication.java[tag=add]
----

登录 h2 控制台。http://localhost:8080/h2-console/ ，账号密码都是：sa。我们可以看到，

* PERSON 表：10 条记录。
* PERSON_PROVINCE_0 表： 0 条记录。
* PERSON_PROVINCE_1 表： 2 条记录，包含上海。
* PERSON_PROVINCE_2 表： 3 条记录，包含浙江，安徽。
* PERSON_PROVINCE_3 表： 0 条记录。
* PERSON_PROVINCE_4 表： 3 条记录，包含陕西，四川。
* PERSON_PROVINCE_5 表： 2 条记录，包含北京。

从上面可以看出，已经实现了分库分表，即同一省份的记录肯定在同一张表中。这里 PERSON_PROVINCE_4 表中包含了两个省份，时因为我们使用 哈希取余 算法。 不同省份有可能会在一张表中，但一个省份只能在一张表中。

另外，我们可以调用提供的增删改查接口来测试。

