spring:
  h2:
    console:
      path: /h2-console
      enabled: true
#  shardingsphere:
#    datasource:
#      names: db0
#      db0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: org.h2.Driver
#        jdbc-url: jdbc:h2:mem:test
#        username: sa
#        password: sa
#    mode:
#      type: Standalone
#    rules:
#      sharding:
#        binding-tables:
#          - person_province
#        sharding-algorithms:
#          person-province-algorithm:
#            type: HASH_MOD
#            props:
#              sharding-count: '6'
#        tables:
#          person_province:
#            actual-data-nodes: db0.person_province_$->{0..5}
#            table-strategy:
#              standard:
#                sharding-algorithm-name: person-province-algorithm
#                sharding-column: province
