spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      path: /h2-console
      enabled: true
#debug: true
sharding:
  tables:
    - table: person_province
      sharding-algorithms:
        name: person-province-algorithm
        sharding-count: 6
        sharding-type: hash
      sharding-column: province