spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    password: sa
    username:

  h2:
    console:
      path: /h2-console
      enabled: true

